### ISSUE TITLE
Activation of extension not working

### ISSUE THREAD

**Issue by benedictdudel** [Bixie/pagekit-framework#3]
Hey,

I just tried your new version but it seems that I can't enable it at the backend of pagekit. I am sorry but there isn't even an error message (Debug enabled).

On an existing pagekit installation where the framework is already enabled, the framework is running fine after update.

**Comment by benedictdudel** [comment]
My fail. Don't worry.

**Comment by malles** [comment]
This is a bit of a problem indeed. When first installing an extension that requires the framework, it cannot be enabled, because the framework isn't enabled. 
Refreshing the extension page and enebling them both will work. 

In the new PK version, there will be an error message, saying framework must be enabled.
